services:
  kvuno:
    container_name: kvuno
    hostname: kvuno
    image: masgeek/kvuno-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
#    environment:
#      FLASK_ENV: development
#      DB_URL: ${DB_URL}
#      LOG_LEVEL: ${LOG_LEVEL:-info}
#      DEBUG_DB: ${LOG_LEVEL:-0}
#    depends_on:
#      - db
#    networks:
#      - my_network

  db:
    container_name: db
    hostname: db
    image: mariadb:11.0.3
    restart: unless-stopped
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: ${ROOT_PASS:-root}
      MARIADB_DATABASE: ${DB_NAME:-agwise_api}
      MARIADB_USER: ${DB_USER:-root}
      MARIADB_PASSWORD: ${DB_PASS:-root}
    ports:
      - "3306:3306"
    #    volumes:
    #      - "./sql-migration/kvuno.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - my_network

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
    #      ADMINER_DEFAULT_DB_NAME: ${DB_SERVICE}
    #      ADMINER_DESIGN: ${THEME}
    #      ADMINER_PLUGINS: ${PLUGINS}
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network: