[project]
name = "kvuno-api"
version = "1.0.1"
description = ""
authors = [
    {name = "Munywele Sammy Barasa",email = "sammy@munywele.co.ke"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pyreadr (>=0.5.3,<0.6.0)",
    "pandas (>=2.3.2,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "flask (>=3.1.2,<4.0.0)",
    "flask-openapi3[all] (>=4.2.1,<5.0.0)",
    "flask-limiter (>=3.12,<4.0)",
    "waitress (>=3.0.2,<4.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "pymysql (>=1.1.2,<2.0.0)",
    "flask-cors (>=6.0.1,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
alembic = "^1.16.4"
pylint = "^3.3.8"
sqlacodegen = {version = "^3.1.0", extras = ["geoalchemy2"]}

